[((title . "What are good tools for Emacs package development?")
  (link . "http://emacs.stackexchange.com/questions/2949/what-are-good-tools-for-emacs-package-development")
  (question_id . 2949)
  (creation_date . 1414816866)
  (last_activity_date . 1414816866)
  (score . 0)
  (answer_count . 1)
  (view_count . 6)
  (is_answered . :json-false)
  (owner
   (link . "http://emacs.stackexchange.com/users/2264/sean-allred")
   (display_name . "Sean Allred")
   (accept_rate . 75)
   (user_type . "registered")
   (user_id . 2264)
   (reputation . 543))
  (tags . ["elisp" "interactive-development" "package-development"]))
((title . "Is there a &#39;local undo&#39; extension for Emacs?")
 (link . "http://emacs.stackexchange.com/questions/2946/is-there-a-local-undo-extension-for-emacs")
 (question_id . 2946)
 (creation_date . 1414810154)
 (last_activity_date . 1414813323)
 (score . 3)
 (answer_count . 1)
 (accepted_answer_id . 2948)
 (view_count . 10)
 (is_answered . t)
 (owner
  (link . "http://emacs.stackexchange.com/users/600/mcb")
  (display_name . "mcb")
  (user_type . "registered")
  (user_id . 600)
  (reputation . 188))
 (tags . ["editing"]))
((title . "Helm color theme gets mixed results")
 (link . "http://emacs.stackexchange.com/questions/2937/helm-color-theme-gets-mixed-results")
 (question_id . 2937)
 (creation_date . 1414795519)
 (last_activity_date . 1414813299)
 (score . 0)
 (answer_count . 2)
 (view_count . 16)
 (is_answered . t)
 (owner
  (link . "http://emacs.stackexchange.com/users/35/ryan")
  (display_name . "Ryan")
  (user_type . "registered")
  (user_id . 35)
  (reputation . 255))
 (tags . ["helm" "themes"]))
((title . "`url-inhibit-uncompression` is ineffective; emulating curl with url.el")
 (link . "http://emacs.stackexchange.com/questions/2947/url-inhibit-uncompression-is-ineffective-emulating-curl-with-url-el")
 (question_id . 2947)
 (creation_date . 1414812397)
 (last_activity_date . 1414812397)
 (score . 0)
 (answer_count . 0)
 (view_count . 3)
 (is_answered . :json-false)
 (owner
  (link . "http://emacs.stackexchange.com/users/2264/sean-allred")
  (display_name . "Sean Allred")
  (accept_rate . 75)
  (user_type . "registered")
  (user_id . 2264)
  (reputation . 543))
 (tags . ["compression" "url"]))
((title . "How can I bring back `nil`?")
 (link . "http://emacs.stackexchange.com/questions/2935/how-can-i-bring-back-nil")
 (question_id . 2935)
 (last_edit_date . 1414799073)
 (creation_date . 1414792387)
 (last_activity_date . 1414805588)
 (score . 5)
 (answer_count . 1)
 (accepted_answer_id . 2938)
 (view_count . 133)
 (is_answered . t)
 (owner
  (link . "http://emacs.stackexchange.com/users/2264/sean-allred")
  (display_name . "Sean Allred")
  (accept_rate . 75)
  (user_type . "registered")
  (user_id . 2264)
  (reputation . 543))
 (tags . ["elisp" "interactive-development"]))
((title . "org babel eval with no confirmation is explicit: :eval yes")
 (link . "http://emacs.stackexchange.com/questions/2945/org-babel-eval-with-no-confirmation-is-explicit-eval-yes")
 (question_id . 2945)
 (creation_date . 1414805111)
 (last_activity_date . 1414805111)
 (score . 0)
 (answer_count . 0)
 (view_count . 5)
 (is_answered . :json-false)
 (owner
  (link . "http://emacs.stackexchange.com/users/55/wdkrnls")
  (display_name . "wdkrnls")
  (accept_rate . 100)
  (user_type . "registered")
  (user_id . 55)
  (reputation . 362))
 (tags . ["org-mode" "org-babel"]))
((title . "Interpratation of Tabs in text copied from Emacs and pasted in other programs/editors")
 (link . "http://emacs.stackexchange.com/questions/2944/interpratation-of-tabs-in-text-copied-from-emacs-and-pasted-in-other-programs-ed")
 (question_id . 2944)
 (creation_date . 1414804977)
 (last_activity_date . 1414804977)
 (score . 0)
 (answer_count . 0)
 (view_count . 5)
 (is_answered . :json-false)
 (owner
  (link . "http://emacs.stackexchange.com/users/2248/adam")
  (display_name . "Adam")
  (accept_rate . 80)
  (user_type . "registered")
  (user_id . 2248)
  (reputation . 227))
 (tags . ["gnu-emacs"]))
((title . "Calling the calc stack from babel: displaying percentages")
 (link . "http://emacs.stackexchange.com/questions/2943/calling-the-calc-stack-from-babel-displaying-percentages")
 (question_id . 2943)
 (creation_date . 1414804647)
 (last_activity_date . 1414804647)
 (score . 0)
 (answer_count . 0)
 (view_count . 2)
 (is_answered . :json-false)
 (owner
  (link . "http://emacs.stackexchange.com/users/55/wdkrnls")
  (display_name . "wdkrnls")
  (accept_rate . 100)
  (user_type . "registered")
  (user_id . 55)
  (reputation . 362))
 (tags . ["org-mode" "org-babel" "calc"]))
((title . "eldoc in python-mode")
 (link . "http://emacs.stackexchange.com/questions/2942/eldoc-in-python-mode")
 (question_id . 2942)
 (creation_date . 1414800979)
 (last_activity_date . 1414800979)
 (score . 1)
 (answer_count . 0)
 (view_count . 9)
 (is_answered . :json-false)
 (owner
  (link . "http://emacs.stackexchange.com/users/2191/nathaniel-flath")
  (display_name . "Nathaniel Flath")
  (accept_rate . 40)
  (user_type . "registered")
  (user_id . 2191)
  (reputation . 170))
 (tags . ["python" "eldoc" "customization"]))
((title . "god-mode: swap keys")
 (link . "http://emacs.stackexchange.com/questions/2903/god-mode-swap-keys")
 (question_id . 2903)
 (creation_date . 1414755674)
 (last_activity_date . 1414800498)
 (score . 2)
 (answer_count . 2)
 (accepted_answer_id . 2941)
 (view_count . 42)
 (is_answered . t)
 (owner
  (link . "http://emacs.stackexchange.com/users/2005/rekado")
  (display_name . "rekado")
  (user_type . "registered")
  (user_id . 2005)
  (reputation . 875))
 (tags . ["key-bindings" "keymap" "god-mode"]))
((title . "How to make `truncate-lines` nil and `auto-fill-mode` off in magit buffers")
 (link . "http://emacs.stackexchange.com/questions/2890/how-to-make-truncate-lines-nil-and-auto-fill-mode-off-in-magit-buffers")
 (question_id . 2890)
 (last_edit_date . 1414798728)
 (creation_date . 1414730361)
 (last_activity_date . 1414798728)
 (score . 0)
 (answer_count . 1)
 (accepted_answer_id . 2895)
 (view_count . 23)
 (is_answered . t)
 (owner
  (link . "http://emacs.stackexchange.com/users/794/codychan")
  (display_name . "CodyChan")
  (user_type . "registered")
  (user_id . 794)
  (reputation . 125))
 (tags . ["magit"]))
((title . "How can I determine if a file is compressed from Elisp?")
 (link . "http://emacs.stackexchange.com/questions/2931/how-can-i-determine-if-a-file-is-compressed-from-elisp")
 (question_id . 2931)
 (last_edit_date . 1414798025)
 (creation_date . 1414789578)
 (last_activity_date . 1414798025)
 (score . 1)
 (answer_count . 0)
 (view_count . 18)
 (is_answered . :json-false)
 (owner
  (link . "http://emacs.stackexchange.com/users/2264/sean-allred")
  (display_name . "Sean Allred")
  (accept_rate . 75)
  (user_type . "registered")
  (user_id . 2264)
  (reputation . 543))
 (tags . ["compression" "url"]))
((title . "Focus-hook: attenuate colours when losing focus")
 (link . "http://emacs.stackexchange.com/questions/2922/focus-hook-attenuate-colours-when-losing-focus")
 (question_id . 2922)
 (last_edit_date . 1414793447)
 (creation_date . 1414774490)
 (last_activity_date . 1414793447)
 (score . 3)
 (answer_count . 0)
 (view_count . 20)
 (is_answered . :json-false)
 (owner
  (link . "http://emacs.stackexchange.com/users/2005/rekado")
  (display_name . "rekado")
  (user_type . "registered")
  (user_id . 2005)
  (reputation . 875))
 (tags . ["frames" "hooks" "focus"]))
((title . "&quot;Making tag completion table&quot; Freezes/Blocks -- how to disable")
 (link . "http://emacs.stackexchange.com/questions/2919/making-tag-completion-table-freezes-blocks-how-to-disable")
 (question_id . 2919)
 (creation_date . 1414770468)
 (last_activity_date . 1414793088)
 (score . 2)
 (answer_count . 1)
 (view_count . 21)
 (is_answered . :json-false)
 (owner
  (link . "http://emacs.stackexchange.com/users/2265/cheezy")
  (display_name . "cheezy")
  (user_type . "registered")
  (user_id . 2265)
  (reputation . 11))
 (tags . ["autocomplete" "performance" "ctags"]))
((title . "Open edit-server files from emacsclient in a specific frame")
 (link . "http://emacs.stackexchange.com/questions/2417/open-edit-server-files-from-emacsclient-in-a-specific-frame")
 (question_id . 2417)
 (last_edit_date . 1413990607)
 (creation_date . 1413927107)
 (last_activity_date . 1414790834)
 (score . 5)
 (answer_count . 2)
 (view_count . 47)
 (is_answered . t)
 (owner
  (link . "http://emacs.stackexchange.com/users/93/nispio")
  (display_name . "nispio")
  (accept_rate . 55)
  (user_type . "registered")
  (user_id . 93)
  (reputation . 1714))
 (tags . ["frames" "emacsclient"]))
((title . "Babel doesn&#39;t wrap results in verbatim")
 (link . "http://emacs.stackexchange.com/questions/2920/babel-doesnt-wrap-results-in-verbatim")
 (question_id . 2920)
 (last_edit_date . 1414770962)
 (creation_date . 1414770503)
 (last_activity_date . 1414784968)
 (score . 0)
 (answer_count . 1)
 (view_count . 16)
 (is_answered . :json-false)
 (owner
  (link . "http://emacs.stackexchange.com/users/563/wvxvw")
  (display_name . "wvxvw")
  (user_type . "registered")
  (user_id . 563)
  (reputation . 255))
 (tags . ["org-mode" "org-export" "org-babel"]))
((title . "Can I change the background color of the inactive minibuffer?")
 (link . "http://emacs.stackexchange.com/questions/2323/can-i-change-the-background-color-of-the-inactive-minibuffer")
 (question_id . 2323)
 (last_edit_date . 1413635904)
 (creation_date . 1413626421)
 (last_activity_date . 1414784512)
 (score . 8)
 (answer_count . 2)
 (view_count . 93)
 (is_answered . t)
 (owner
  (link . "http://emacs.stackexchange.com/users/600/mcb")
  (display_name . "mcb")
  (user_type . "registered")
  (user_id . 600)
  (reputation . 188))
 (tags . ["customize" "faces" "minibuffer"]))
((title . "Projectile project in folder without write access?")
 (link . "http://emacs.stackexchange.com/questions/2891/projectile-project-in-folder-without-write-access")
 (question_id . 2891)
 (creation_date . 1414735834)
 (last_activity_date . 1414784284)
 (score . 2)
 (answer_count . 2)
 (view_count . 33)
 (is_answered . t)
 (owner
  (link . "http://emacs.stackexchange.com/users/93/nispio")
  (display_name . "nispio")
  (accept_rate . 55)
  (user_type . "registered")
  (user_id . 93)
  (reputation . 1714))
 (tags . ["projectile"]))
((title . "How to disable eldoc for `eval-expression`?")
 (link . "http://emacs.stackexchange.com/questions/2917/how-to-disable-eldoc-for-eval-expression")
 (question_id . 2917)
 (last_edit_date . 1414770569)
 (creation_date . 1414767244)
 (last_activity_date . 1414776394)
 (score . 1)
 (answer_count . 1)
 (accepted_answer_id . 2918)
 (view_count . 35)
 (is_answered . t)
 (owner
  (link . "http://emacs.stackexchange.com/users/2094/abo-abo")
  (display_name . "abo-abo")
  (user_type . "registered")
  (user_id . 2094)
  (reputation . 430))
 (tags . ["elisp" "emacs-25"]))
((title . "How to view and edit large delimiter separated value files?")
 (link . "http://emacs.stackexchange.com/questions/972/how-to-view-and-edit-large-delimiter-separated-value-files")
 (question_id . 972)
 (last_edit_date . 1414713136)
 (creation_date . 1412881152)
 (last_activity_date . 1414775451)
 (score . 6)
 (answer_count . 1)
 (accepted_answer_id . 2923)
 (view_count . 93)
 (is_answered . t)
 (owner
  (link . "http://emacs.stackexchange.com/users/315/holocronweaver")
  (display_name . "holocronweaver")
  (user_type . "registered")
  (user_id . 315)
  (reputation . 55))
 (tags . ["editing" "table" "large-files" "csv"]))
((title . "The old &quot;how to fold xml&quot; question")
 (link . "http://emacs.stackexchange.com/questions/2884/the-old-how-to-fold-xml-question")
 (question_id . 2884)
 (creation_date . 1414720950)
 (last_activity_date . 1414773563)
 (score . 5)
 (answer_count . 1)
 (view_count . 26)
 (is_answered . t)
 (owner
  (link . "http://emacs.stackexchange.com/users/215/mark-aufflick")
  (display_name . "Mark Aufflick")
  (user_type . "registered")
  (user_id . 215)
  (reputation . 203))
 (tags . ["xml" "nxml" "outline"]))
((title . "How can I turn [1..10] into [1,2,3,4,5,6,7,8,9,10] in calc?")
 (link . "http://emacs.stackexchange.com/questions/2914/how-can-i-turn-1-10-into-1-2-3-4-5-6-7-8-9-10-in-calc")
 (question_id . 2914)
 (creation_date . 1414765664)
 (last_activity_date . 1414766835)
 (score . 3)
 (answer_count . 1)
 (accepted_answer_id . 2916)
 (view_count . 105)
 (is_answered . t)
 (owner
  (link . "http://emacs.stackexchange.com/users/503/mrbones")
  (display_name . "MrBones")
  (user_type . "registered")
  (user_id . 503)
  (reputation . 118))
 (tags . ["calc"]))
((title . "How to turn off &quot;error&quot; highlighting in emacs-lisp-mode for Emacs 25?")
 (link . "http://emacs.stackexchange.com/questions/2907/how-to-turn-off-error-highlighting-in-emacs-lisp-mode-for-emacs-25")
 (question_id . 2907)
 (last_edit_date . 1414766064)
 (creation_date . 1414759846)
 (last_activity_date . 1414766064)
 (score . 2)
 (answer_count . 1)
 (accepted_answer_id . 2913)
 (view_count . 50)
 (is_answered . t)
 (owner
  (link . "http://emacs.stackexchange.com/users/2094/abo-abo")
  (display_name . "abo-abo")
  (user_type . "registered")
  (user_id . 2094)
  (reputation . 430))
 (tags . ["elisp" "font-lock" "emacs-lisp-mode"]))
((title . "Kill buffer when frame is deleted")
 (link . "http://emacs.stackexchange.com/questions/2888/kill-buffer-when-frame-is-deleted")
 (question_id . 2888)
 (creation_date . 1414725672)
 (last_activity_date . 1414765666)
 (score . 5)
 (answer_count . 3)
 (accepted_answer_id . 2915)
 (view_count . 61)
 (is_answered . t)
 (owner
  (link . "http://emacs.stackexchange.com/users/163/dharmatech")
  (display_name . "dharmatech")
  (user_type . "registered")
  (user_id . 163)
  (reputation . 216))
 (tags . ["buffers" "frames"]))
((title . "Is there a better way to handle multiline docstrings in elisp?")
 (link . "http://emacs.stackexchange.com/questions/2887/is-there-a-better-way-to-handle-multiline-docstrings-in-elisp")
 (question_id . 2887)
 (last_edit_date . 1414741213)
 (creation_date . 1414725439)
 (last_activity_date . 1414764354)
 (score . 7)
 (answer_count . 3)
 (view_count . 104)
 (is_answered . t)
 (owner
  (link . "http://emacs.stackexchange.com/users/2345/krazy-glew")
  (display_name . "Krazy Glew")
  (user_type . "registered")
  (user_id . 2345)
  (reputation . 136))
 (tags . ["elisp" "documentation"]))
((title . "TAB does not auto-indent lines anymore")
 (link . "http://emacs.stackexchange.com/questions/2904/tab-does-not-auto-indent-lines-anymore")
 (question_id . 2904)
 (last_edit_date . 1414760438)
 (creation_date . 1414757159)
 (last_activity_date . 1414760438)
 (score . 1)
 (answer_count . 0)
 (view_count . 30)
 (is_answered . :json-false)
 (owner
  (link . "http://emacs.stackexchange.com/users/2305/vivian-maya")
  (display_name . "Vivian Maya")
  (user_type . "registered")
  (user_id . 2305)
  (reputation . 81))
 (tags . ["indentation"]))
((title . "Password/Key Management for multiple machines in emacs")
 (link . "http://emacs.stackexchange.com/questions/2902/password-key-management-for-multiple-machines-in-emacs")
 (question_id . 2902)
 (creation_date . 1414755561)
 (last_activity_date . 1414760173)
 (score . 7)
 (answer_count . 1)
 (view_count . 64)
 (is_answered . t)
 (owner
  (link . "http://emacs.stackexchange.com/users/294/gambo")
  (display_name . "Gambo")
  (user_type . "registered")
  (user_id . 294)
  (reputation . 175))
 (tags . ["tramp"]))
((title . "&quot;Symbol&#39;s function definition is void: cl-macroexpand-all&quot; when trying to install php-mode")
 (link . "http://emacs.stackexchange.com/questions/2864/symbols-function-definition-is-void-cl-macroexpand-all-when-trying-to-instal")
 (question_id . 2864)
 (last_edit_date . 1414701459)
 (creation_date . 1414700357)
 (last_activity_date . 1414759512)
 (score . 2)
 (answer_count . 2)
 (accepted_answer_id . 2866)
 (view_count . 29)
 (is_answered . t)
 (owner
  (link . "http://emacs.stackexchange.com/users/2342/cg433n")
  (display_name . "cg433n")
  (user_type . "registered")
  (user_id . 2342)
  (reputation . 13))
 (tags . ["package" "cl-lib" "php-mode"]))
((title . "Better debugging of crashing Emacs?")
 (link . "http://emacs.stackexchange.com/questions/363/better-debugging-of-crashing-emacs")
 (question_id . 363)
 (last_edit_date . 1411830937)
 (creation_date . 1411809580)
 (last_activity_date . 1414757838)
 (score . 5)
 (answer_count . 2)
 (accepted_answer_id . 373)
 (view_count . 65)
 (is_answered . t)
 (owner
  (link . "http://emacs.stackexchange.com/users/249/gsl")
  (display_name . "gsl")
  (accept_rate . 100)
  (user_type . "registered")
  (user_id . 249)
  (reputation . 84))
 (tags . ["elisp" "fonts" "debugging" "crash"]))
((title . "org-mode and reftex giving this error: reftex-using-biblatex-p: Stack overflow in regexp matcher")
 (link . "http://emacs.stackexchange.com/questions/2901/org-mode-and-reftex-giving-this-error-reftex-using-biblatex-p-stack-overflow-i")
 (question_id . 2901)
 (last_edit_date . 1414754843)
 (creation_date . 1414754222)
 (last_activity_date . 1414754843)
 (score . 0)
 (answer_count . 0)
 (view_count . 11)
 (is_answered . :json-false)
 (owner
  (link . "http://emacs.stackexchange.com/users/201/petrux")
  (display_name . "petrux")
  (user_type . "registered")
  (user_id . 201)
  (reputation . 41))
 (tags . ["org-mode" "reftex-mode" "bibtex"]))]
