((title . "Can I mark inbox items as read in api v2.2?")
 (link . "http://stackapps.com/posts/comments/12080?noredirect=1")
 (item_type . "comment")
 (question_id . 5059)
 (comment_id . 12080)
 (creation_date . 1419153905)
 (is_unread . :json-false)
 (site (site_type . "main_site")
       (name . "Stack Apps")
       (api_site_parameter . "stackapps")
       (site_url . "http://stackapps.com")
       (favicon_url . "http://cdn.sstatic.net/stackapps/img/favicon.ico")
       (styling (link_color . "#0077DD") (tag_foreground_color . "#555555") (tag_background_color . "#E7ECEC"))))
