(((site_type . "main_site")
  (name . "Stack Overflow")
  (logo_url . "http://cdn.sstatic.net/stackoverflow/img/logo.png")
  (api_site_parameter . "stackoverflow")
  (site_url . "http://stackoverflow.com")
  (audience . "professional and enthusiast programmers")
  (icon_url . "http://cdn.sstatic.net/stackoverflow/img/apple-touch-icon.png")
  (favicon_url . "http://cdn.sstatic.net/stackoverflow/img/favicon.ico")
  (high_resolution_icon_url . "http://cdn.sstatic.net/stackoverflow/img/apple-touch-icon@2.png")
  (site_state . "normal")
  (launch_date . 1221436800)
  (markdown_extensions . ("Prettify"))
  (aliases . ("http://www.stackoverflow.com" "http://facebook.stackoverflow.com"))
  (related_sites . (((name . "Meta Stack Overflow")
		     (site_url . "http://meta.stackoverflow.com")
		     (api_site_parameter . "meta.stackoverflow")
		     (relation . "meta"))
		    ((name . "Stack Overflow Chat")
		     (site_url . "http://chat.stackoverflow.com")
		     (relation . "chat"))))
  (styling
   (link_color . "#0077CC")
   (tag_foreground_color . "#3E6D8E")
   (tag_background_color . "#E0EAF1")))
 ((site_type . "main_site")
  (name . "Server Fault")
  (logo_url . "http://cdn.sstatic.net/serverfault/img/logo.png")
  (api_site_parameter . "serverfault")
  (site_url . "http://serverfault.com")
  (audience . "professional system and network administrators")
  (icon_url . "http://cdn.sstatic.net/serverfault/img/apple-touch-icon.png")
  (favicon_url . "http://cdn.sstatic.net/serverfault/img/favicon.ico")
  (twitter_account . "ServerFault")
  (high_resolution_icon_url . "http://cdn.sstatic.net/serverfault/img/apple-touch-icon@2.png")
  (site_state . "normal")
  (launch_date . 1243296000)
  (markdown_extensions . ("Prettify"))
  (related_sites . (((name . "Meta Server Fault")
		     (site_url . "http://meta.serverfault.com")
		     (api_site_parameter . "meta.serverfault")
		     (relation . "meta"))
		    ((name . "Chat Stack Exchange")
		     (site_url . "http://chat.stackexchange.com")
		     (relation . "chat"))))
  (styling
   (link_color . "#10456A")
   (tag_foreground_color . "#444444")
   (tag_background_color . "#F3F1D9")))
 ((site_type . "main_site")
  (name . "Super User")
  (logo_url . "http://cdn.sstatic.net/superuser/img/logo.png")
  (api_site_parameter . "superuser")
  (site_url . "http://superuser.com")
  (audience . "computer enthusiasts and power users")
  (icon_url . "http://cdn.sstatic.net/superuser/img/apple-touch-icon.png")
  (favicon_url . "http://cdn.sstatic.net/superuser/img/favicon.ico")
  (twitter_account . "super_user")
  (high_resolution_icon_url . "http://cdn.sstatic.net/superuser/img/apple-touch-icon@2.png")
  (site_state . "normal")
  (launch_date . 1250553600)
  (markdown_extensions . ("Prettify"))
  (related_sites . (((name . "Meta Super User")
		     (site_url . "http://meta.superuser.com")
		     (api_site_parameter . "meta.superuser")
		     (relation . "meta"))
		    ((name . "Chat Stack Exchange")
		     (site_url . "http://chat.stackexchange.com")
		     (relation . "chat"))))
  (styling
   (link_color . "#1086A4")
   (tag_foreground_color . "#1087A4")
   (tag_background_color . "#FFFFFF")))
 ((site_type . "main_site")
  (name . "Meta Stack Exchange")
  (logo_url . "http://cdn.sstatic.net/stackexchangemeta/img/logo.png")
  (api_site_parameter . "meta")
  (site_url . "http://meta.stackexchange.com")
  (audience . "meta-discussion of the Stack Exchange family of Q&amp;A websites")
  (icon_url . "http://cdn.sstatic.net/stackexchangemeta/img/apple-touch-icon.png")
  (favicon_url . "http://cdn.sstatic.net/stackexchangemeta/img/favicon.ico")
  (high_resolution_icon_url . "http://cdn.sstatic.net/stackexchangemeta/img/apple-touch-icon@2.png")
  (site_state . "normal")
  (launch_date . 1246147200)
  (markdown_extensions . ("Prettify"))
  (related_sites . (((name . "Meta Stack Exchange Chat")
		     (site_url . "http://chat.meta.stackexchange.com")
		     (relation . "chat"))))
  (styling
   (link_color . "#4E82C2")
   (tag_foreground_color . "#566E76")
   (tag_background_color . "#F7FDFF")))
 ((site_type . "main_site")
  (name . "Web Applications")
  (logo_url . "http://cdn.sstatic.net/webapps/img/logo.png")
  (api_site_parameter . "webapps")
  (site_url . "http://webapps.stackexchange.com")
  (audience . "power users of web applications")
  (icon_url . "http://cdn.sstatic.net/webapps/img/apple-touch-icon.png")
  (favicon_url . "http://cdn.sstatic.net/webapps/img/favicon.ico")
  (twitter_account . "StackWebApps")
  (high_resolution_icon_url . "http://cdn.sstatic.net/webapps/img/apple-touch-icon@2.png")
  (site_state . "normal")
  (closed_beta_date . 1277856000)
  (open_beta_date . 1278460800)
  (launch_date . 1285804800)
  (aliases . ("http://nothingtoinstall.com"))
  (related_sites . (((name . "Web Applications Meta Stack Exchange")
		     (site_url . "http://meta.webapps.stackexchange.com")
		     (api_site_parameter . "meta.webapps")
		     (relation . "meta"))
		    ((name . "Chat Stack Exchange")
		     (site_url . "http://chat.stackexchange.com")
		     (relation . "chat"))))
  (styling
   (link_color . "#426389")
   (tag_foreground_color . "#5D7A9C")
   (tag_background_color . "#E2EDFA")))
 ((site_type . "meta_site")
  (name . "Web Applications Meta")
  (logo_url . "http://cdn.sstatic.net/webappsmeta/img/logo.png")
  (api_site_parameter . "meta.webapps")
  (site_url . "http://meta.webapps.stackexchange.com")
  (audience . "power users of web applications")
  (icon_url . "http://cdn.sstatic.net/webappsmeta/img/apple-touch-icon.png")
  (favicon_url . "http://cdn.sstatic.net/webappsmeta/img/favicon.ico")
  (high_resolution_icon_url . "http://cdn.sstatic.net/webappsmeta/img/apple-touch-icon@2.png")
  (site_state . "linked_meta")
  (aliases . ("http://meta.nothingtoinstall.com"))
  (related_sites . (((name . "Web Applications Stack Exchange")
		     (site_url . "http://webapps.stackexchange.com")
		     (api_site_parameter . "webapps")
		     (relation . "parent"))
		    ((name . "Chat Stack Exchange")
		     (site_url . "http://chat.stackexchange.com")
		     (relation . "chat"))))
  (styling
   (link_color . "#333C43")
   (tag_foreground_color . "#666")
   (tag_background_color . "#EBEBEB")))
 ((site_type . "main_site")
  (name . "Arqade")
  (logo_url . "http://cdn.sstatic.net/gaming/img/logo.png")
  (api_site_parameter . "gaming")
  (site_url . "http://gaming.stackexchange.com")
  (audience . "passionate videogamers on all platforms")
  (icon_url . "http://cdn.sstatic.net/gaming/img/apple-touch-icon.png")
  (favicon_url . "http://cdn.sstatic.net/gaming/img/favicon.ico")
  (twitter_account . "TheArqade")
  (high_resolution_icon_url . "http://cdn.sstatic.net/gaming/img/apple-touch-icon@2.png")
  (site_state . "normal")
  (closed_beta_date . 1278460800)
  (open_beta_date . 1279065600)
  (launch_date . 1286323200)
  (aliases . ("http://arqade.com" "http://thearqade.com"))
  (related_sites . (((name . "Arqade Meta")
		     (site_url . "http://meta.gaming.stackexchange.com")
		     (api_site_parameter . "meta.gaming")
		     (relation . "meta"))
		    ((name . "Chat Stack Exchange")
		     (site_url . "http://chat.stackexchange.com")
		     (relation . "chat"))))
  (styling
   (link_color . "#5A8F53")
   (tag_foreground_color . "#666")
   (tag_background_color . "#FFF")))
 ((site_type . "meta_site")
  (name . "Arqade Meta")
  (logo_url . "http://cdn.sstatic.net/gamingmeta/img/logo.png")
  (api_site_parameter . "meta.gaming")
  (site_url . "http://meta.gaming.stackexchange.com")
  (audience . "passionate videogamers on all platforms")
  (icon_url . "http://cdn.sstatic.net/gamingmeta/img/apple-touch-icon.png")
  (favicon_url . "http://cdn.sstatic.net/gamingmeta/img/favicon.ico")
  (high_resolution_icon_url . "http://cdn.sstatic.net/gamingmeta/img/apple-touch-icon@2.png")
  (site_state . "linked_meta")
  (aliases . ("http://meta.arqade.com" "http://meta.thearqade.com"))
  (related_sites . (((name . "Arqade")
		     (site_url . "http://gaming.stackexchange.com")
		     (api_site_parameter . "gaming")
		     (relation . "parent"))
		    ((name . "Chat Stack Exchange")
		     (site_url . "http://chat.stackexchange.com")
		     (relation . "chat"))))
  (styling
   (link_color . "#666666")
   (tag_foreground_color . "#666")
   (tag_background_color . "#FFF")))
 ((site_type . "main_site")
  (name . "Webmasters")
  (logo_url . "http://cdn.sstatic.net/webmasters/img/logo.png")
  (api_site_parameter . "webmasters")
  (site_url . "http://webmasters.stackexchange.com")
  (audience . "pro webmasters")
  (icon_url . "http://cdn.sstatic.net/webmasters/img/apple-touch-icon.png")
  (favicon_url . "http://cdn.sstatic.net/webmasters/img/favicon.ico")
  (twitter_account . "StackWebmasters")
  (high_resolution_icon_url . "http://cdn.sstatic.net/webmasters/img/apple-touch-icon@2.png")
  (site_state . "normal")
  (closed_beta_date . 1278547200)
  (open_beta_date . 1279152000)
  (launch_date . 1286928000)
  (markdown_extensions . ("Prettify"))
  (aliases . ("http://webmaster.stackexchange.com"))
  (related_sites . (((name . "Webmasters Meta Stack Exchange")
		     (site_url . "http://meta.webmasters.stackexchange.com")
		     (api_site_parameter . "meta.webmasters")
		     (relation . "meta"))
		    ((name . "Chat Stack Exchange")
		     (site_url . "http://chat.stackexchange.com")
		     (relation . "chat"))))
  (styling
   (link_color . "#1C69A4")
   (tag_foreground_color . "#1B8FBB")
   (tag_background_color . "#FFF")))
 ((site_type . "meta_site")
  (name . "Webmasters Meta")
  (logo_url . "http://cdn.sstatic.net/webmastersmeta/img/logo.png")
  (api_site_parameter . "meta.webmasters")
  (site_url . "http://meta.webmasters.stackexchange.com")
  (audience . "pro webmasters")
  (icon_url . "http://cdn.sstatic.net/webmastersmeta/img/apple-touch-icon.png")
  (favicon_url . "http://cdn.sstatic.net/webmastersmeta/img/favicon.ico")
  (high_resolution_icon_url . "http://cdn.sstatic.net/webmastersmeta/img/apple-touch-icon@2.png")
  (site_state . "linked_meta")
  (markdown_extensions . ("Prettify"))
  (aliases . ("http://meta.webmaster.stackexchange.com"))
  (related_sites . (((name . "Webmasters Stack Exchange")
		     (site_url . "http://webmasters.stackexchange.com")
		     (api_site_parameter . "webmasters")
		     (relation . "parent"))
		    ((name . "Chat Stack Exchange")
		     (site_url . "http://chat.stackexchange.com")
		     (relation . "chat"))))
  (styling
   (link_color . "#3D3D3D")
   (tag_foreground_color . "#666666")
   (tag_background_color . "#FFF")))
 ((site_type . "main_site")
  (name . "Seasoned Advice")
  (logo_url . "http://cdn.sstatic.net/cooking/img/logo.png")
  (api_site_parameter . "cooking")
  (site_url . "http://cooking.stackexchange.com")
  (audience . "professional and amateur chefs")
  (icon_url . "http://cdn.sstatic.net/cooking/img/apple-touch-icon.png")
  (favicon_url . "http://cdn.sstatic.net/cooking/img/favicon.ico")
  (twitter_account . "StackCooking")
  (high_resolution_icon_url . "http://cdn.sstatic.net/cooking/img/apple-touch-icon@2.png")
  (site_state . "normal")
  (closed_beta_date . 1278633600)
  (open_beta_date . 1279238400)
  (launch_date . 1287014400)
  (aliases . ("http://seasonedadvice.com"))
  (related_sites . (((name . "Seasoned Advice Meta")
		     (site_url . "http://meta.cooking.stackexchange.com")
		     (api_site_parameter . "meta.cooking")
		     (relation . "meta"))
		    ((name . "Chat Stack Exchange")
		     (site_url . "http://chat.stackexchange.com")
		     (relation . "chat"))))
  (styling
   (link_color . "#AB2020")
   (tag_foreground_color . "#847454")
   (tag_background_color . "#FFF5E4")))
 ((site_type . "meta_site")
  (name . "Seasoned Advice Meta")
  (logo_url . "http://cdn.sstatic.net/cookingmeta/img/logo.png")
  (api_site_parameter . "meta.cooking")
  (site_url . "http://meta.cooking.stackexchange.com")
  (audience . "professional and amateur chefs")
  (icon_url . "http://cdn.sstatic.net/cookingmeta/img/apple-touch-icon.png")
  (favicon_url . "http://cdn.sstatic.net/cookingmeta/img/favicon.ico")
  (high_resolution_icon_url . "http://cdn.sstatic.net/cookingmeta/img/apple-touch-icon@2.png")
  (site_state . "linked_meta")
  (aliases . ("http://meta.seasonedadvice.com"))
  (related_sites . (((name . "Seasoned Advice")
		     (site_url . "http://cooking.stackexchange.com")
		     (api_site_parameter . "cooking")
		     (relation . "parent"))
		    ((name . "Chat Stack Exchange")
		     (site_url . "http://chat.stackexchange.com")
		     (relation . "chat"))))
  (styling
   (link_color . "#3D3D3D")
   (tag_foreground_color . "#666666")
   (tag_background_color . "#FFF")))
 ((site_type . "main_site")
  (name . "Game Development")
  (logo_url . "http://cdn.sstatic.net/gamedev/img/logo.png")
  (api_site_parameter . "gamedev")
  (site_url . "http://gamedev.stackexchange.com")
  (audience . "professional and independent game developers")
  (icon_url . "http://cdn.sstatic.net/gamedev/img/apple-touch-icon.png")
  (favicon_url . "http://cdn.sstatic.net/gamedev/img/favicon.ico")
  (twitter_account . "StackGameDev")
  (high_resolution_icon_url . "http://cdn.sstatic.net/gamedev/img/apple-touch-icon@2.png")
  (site_state . "normal")
  (closed_beta_date . 1279065600)
  (open_beta_date . 1279670400)
  (launch_date . 1287619200)
  (markdown_extensions . ("Prettify"))
  (related_sites . (((name . "Game Development Meta Stack Exchange")
		     (site_url . "http://meta.gamedev.stackexchange.com")
		     (api_site_parameter . "meta.gamedev")
		     (relation . "meta"))
		    ((name . "Chat Stack Exchange")
		     (site_url . "http://chat.stackexchange.com")
		     (relation . "chat"))))
  (styling
   (link_color . "#416D63")
   (tag_foreground_color . "#444444")
   (tag_background_color . "#eeeeee")))
 ((site_type . "meta_site")
  (name . "Game Development Meta")
  (logo_url . "http://cdn.sstatic.net/gamedevmeta/img/logo.png")
  (api_site_parameter . "meta.gamedev")
  (site_url . "http://meta.gamedev.stackexchange.com")
  (audience . "professional and independent game developers")
  (icon_url . "http://cdn.sstatic.net/gamedevmeta/img/apple-touch-icon.png")
  (favicon_url . "http://cdn.sstatic.net/gamedevmeta/img/favicon.ico")
  (high_resolution_icon_url . "http://cdn.sstatic.net/gamedevmeta/img/apple-touch-icon@2.png")
  (site_state . "linked_meta")
  (related_sites . (((name . "Game Development Stack Exchange")
		     (site_url . "http://gamedev.stackexchange.com")
		     (api_site_parameter . "gamedev")
		     (relation . "parent"))
		    ((name . "Chat Stack Exchange")
		     (site_url . "http://chat.stackexchange.com")
		     (relation . "chat"))))
  (styling
   (link_color . "#3D3D3D")
   (tag_foreground_color . "#666666")
   (tag_background_color . "#FFF")))
 ((site_type . "main_site")
  (name . "Photography")
  (logo_url . "http://cdn.sstatic.net/photo/img/logo.png")
  (api_site_parameter . "photo")
  (site_url . "http://photo.stackexchange.com")
  (audience . "professional, enthusiast and amateur photographers")
  (icon_url . "http://cdn.sstatic.net/photo/img/apple-touch-icon.png")
  (favicon_url . "http://cdn.sstatic.net/photo/img/favicon.ico")
  (twitter_account . "StackPhotos")
  (high_resolution_icon_url . "http://cdn.sstatic.net/photo/img/apple-touch-icon@2.png")
  (site_state . "normal")
  (closed_beta_date . 1279152000)
  (open_beta_date . 1279756800)
  (launch_date . 1288224000)
  (aliases . ("http://photography.stackexchange.com" "http://photos.stackexchange.com"))
  (related_sites . (((name . "Photography Meta Stack Exchange")
		     (site_url . "http://meta.photo.stackexchange.com")
		     (api_site_parameter . "meta.photo")
		     (relation . "meta"))
		    ((name . "Chat Stack Exchange")
		     (site_url . "http://chat.stackexchange.com")
		     (relation . "chat"))))
  (styling
   (link_color . "#0077CC")
   (tag_foreground_color . "#444")
   (tag_background_color . "#F7F7F7")))
 ((site_type . "meta_site")
  (name . "Photography Meta")
  (logo_url . "http://cdn.sstatic.net/photometa/img/logo.png")
  (api_site_parameter . "meta.photo")
  (site_url . "http://meta.photo.stackexchange.com")
  (audience . "professional, enthusiast and amateur photographers")
  (icon_url . "http://cdn.sstatic.net/photometa/img/apple-touch-icon.png")
  (favicon_url . "http://cdn.sstatic.net/photometa/img/favicon.ico")
  (high_resolution_icon_url . "http://cdn.sstatic.net/photometa/img/apple-touch-icon@2.png")
  (site_state . "linked_meta")
  (aliases . ("http://meta.photography.stackexchange.com" "http://meta.photos.stackexchange.com"))
  (related_sites . (((name . "Photography Stack Exchange")
		     (site_url . "http://photo.stackexchange.com")
		     (api_site_parameter . "photo")
		     (relation . "parent"))
		    ((name . "Chat Stack Exchange")
		     (site_url . "http://chat.stackexchange.com")
		     (relation . "chat"))))
  (styling
   (link_color . "#3D3D3D")
   (tag_foreground_color . "#666666")
   (tag_background_color . "#FFF")))
 ((site_type . "main_site")
  (name . "Cross Validated")
  (logo_url . "http://cdn.sstatic.net/stats/img/logo.png")
  (api_site_parameter . "stats")
  (site_url . "http://stats.stackexchange.com")
  (audience . "people interested in statistics, machine learning, data analysis, data mining, and data visualization")
  (icon_url . "http://cdn.sstatic.net/stats/img/apple-touch-icon.png")
  (favicon_url . "http://cdn.sstatic.net/stats/img/favicon.ico")
  (twitter_account . "StackStats")
  (high_resolution_icon_url . "http://cdn.sstatic.net/stats/img/apple-touch-icon@2.png")
  (site_state . "normal")
  (closed_beta_date . 1279497600)
  (open_beta_date . 1280102400)
  (launch_date . 1288828800)
  (markdown_extensions . ("MathJax" "Prettify"))
  (aliases . ("http://statistics.stackexchange.com" "http://crossvalidated.com"))
  (related_sites . (((name . "Cross Validated Meta")
		     (site_url . "http://meta.stats.stackexchange.com")
		     (api_site_parameter . "meta.stats")
		     (relation . "meta"))
		    ((name . "Chat Stack Exchange")
		     (site_url . "http://chat.stackexchange.com")
		     (relation . "chat"))))
  (styling
   (link_color . "#0077CC")
   (tag_foreground_color . "#5D5D5D")
   (tag_background_color . "#edefed")))
 ((site_type . "meta_site")
  (name . "Cross Validated Meta")
  (logo_url . "http://cdn.sstatic.net/statsmeta/img/logo.png")
  (api_site_parameter . "meta.stats")
  (site_url . "http://meta.stats.stackexchange.com")
  (audience . "people interested in statistics, machine learning, data analysis, data mining, and data visualization")
  (icon_url . "http://cdn.sstatic.net/statsmeta/img/apple-touch-icon.png")
  (favicon_url . "http://cdn.sstatic.net/statsmeta/img/favicon.ico")
  (high_resolution_icon_url . "http://cdn.sstatic.net/statsmeta/img/apple-touch-icon@2.png")
  (site_state . "linked_meta")
  (markdown_extensions . ("MathJax"))
  (aliases . ("http://meta.statistics.stackexchange.com"))
  (related_sites . (((name . "Cross Validated")
		     (site_url . "http://stats.stackexchange.com")
		     (api_site_parameter . "stats")
		     (relation . "parent"))
		    ((name . "Chat Stack Exchange")
		     (site_url . "http://chat.stackexchange.com")
		     (relation . "chat"))))
  (styling
   (link_color . "#3D3D3D")
   (tag_foreground_color . "#666666")
   (tag_background_color . "#FFF")))
 ((site_type . "main_site")
  (name . "Mathematics")
  (logo_url . "http://cdn.sstatic.net/math/img/logo.png")
  (api_site_parameter . "math")
  (site_url . "http://math.stackexchange.com")
  (audience . "people studying math at any level and professionals in related fields")
  (icon_url . "http://cdn.sstatic.net/math/img/apple-touch-icon.png")
  (favicon_url . "http://cdn.sstatic.net/math/img/favicon.ico")
  (twitter_account . "StackMath")
  (high_resolution_icon_url . "http://cdn.sstatic.net/math/img/apple-touch-icon@2.png")
  (site_state . "normal")
  (closed_beta_date . 1279584000)
  (open_beta_date . 1280188800)
  (launch_date . 1287964800)
  (markdown_extensions . ("MathJax"))
  (aliases . ("http://maths.stackexchange.com" "http://mathematics.stackexchange.com"))
  (related_sites . (((name . "Mathematics Meta Stack Exchange")
		     (site_url . "http://meta.math.stackexchange.com")
		     (api_site_parameter . "meta.math")
		     (relation . "meta"))
		    ((name . "Chat Stack Exchange")
		     (site_url . "http://chat.stackexchange.com")
		     (relation . "chat"))))
  (styling
   (link_color . "#0077CC")
   (tag_foreground_color . "#000")
   (tag_background_color . "#888888")))
 ((site_type . "meta_site")
  (name . "Mathematics Meta")
  (logo_url . "http://cdn.sstatic.net/mathmeta/img/logo.png")
  (api_site_parameter . "meta.math")
  (site_url . "http://meta.math.stackexchange.com")
  (audience . "people studying math at any level and professionals in related fields")
  (icon_url . "http://cdn.sstatic.net/mathmeta/img/apple-touch-icon.png")
  (favicon_url . "http://cdn.sstatic.net/mathmeta/img/favicon.ico")
  (high_resolution_icon_url . "http://cdn.sstatic.net/mathmeta/img/apple-touch-icon@2.png")
  (site_state . "linked_meta")
  (markdown_extensions . ("MathJax"))
  (related_sites . (((name . "Mathematics Stack Exchange")
		     (site_url . "http://math.stackexchange.com")
		     (api_site_parameter . "math")
		     (relation . "parent"))
		    ((name . "Chat Stack Exchange")
		     (site_url . "http://chat.stackexchange.com")
		     (relation . "chat"))))
  (styling
   (link_color . "#3D3D3D")
   (tag_foreground_color . "#666666")
   (tag_background_color . "#FFF")))
 ((site_type . "main_site")
  (name . "Home Improvement")
  (logo_url . "http://cdn.sstatic.net/diy/img/logo.png")
  (api_site_parameter . "diy")
  (site_url . "http://diy.stackexchange.com")
  (audience . "contractors and serious DIYers")
  (icon_url . "http://cdn.sstatic.net/diy/img/apple-touch-icon.png")
  (favicon_url . "http://cdn.sstatic.net/diy/img/favicon.ico")
  (twitter_account . "StackDIY")
  (high_resolution_icon_url . "http://cdn.sstatic.net/diy/img/apple-touch-icon@2.png")
  (site_state . "normal")
  (closed_beta_date . 1279670400)
  (open_beta_date . 1280275200)
  (launch_date . 1299110400)
  (related_sites . (((name . "Home Improvement Meta Stack Exchange")
		     (site_url . "http://meta.diy.stackexchange.com")
		     (api_site_parameter . "meta.diy")
		     (relation . "meta"))
		    ((name . "Chat Stack Exchange")
		     (site_url . "http://chat.stackexchange.com")
		     (relation . "chat"))))
  (styling
   (link_color . "#0077CC")
   (tag_foreground_color . "#696969")
   (tag_background_color . "#f5f5f5")))
 ((site_type . "meta_site")
  (name . "Home Improvement Meta")
  (logo_url . "http://cdn.sstatic.net/diymeta/img/logo.png")
  (api_site_parameter . "meta.diy")
  (site_url . "http://meta.diy.stackexchange.com")
  (audience . "contractors and serious DIYers")
  (icon_url . "http://cdn.sstatic.net/diymeta/img/apple-touch-icon.png")
  (favicon_url . "http://cdn.sstatic.net/diymeta/img/favicon.ico")
  (high_resolution_icon_url . "http://cdn.sstatic.net/diymeta/img/apple-touch-icon@2.png")
  (site_state . "linked_meta")
  (related_sites . (((name . "Home Improvement Stack Exchange")
		     (site_url . "http://diy.stackexchange.com")
		     (api_site_parameter . "diy")
		     (relation . "parent"))
		    ((name . "Chat Stack Exchange")
		     (site_url . "http://chat.stackexchange.com")
		     (relation . "chat"))))
  (styling
   (link_color . "#3D3D3D")
   (tag_foreground_color . "#666666")
   (tag_background_color . "#FFF")))
 ((site_type . "meta_site")
  (name . "Meta Super User")
  (logo_url . "http://cdn.sstatic.net/superusermeta/img/logo.png")
  (api_site_parameter . "meta.superuser")
  (site_url . "http://meta.superuser.com")
  (audience . "computer enthusiasts and power users")
  (icon_url . "http://cdn.sstatic.net/superusermeta/img/apple-touch-icon.png")
  (favicon_url . "http://cdn.sstatic.net/superusermeta/img/favicon.ico")
  (high_resolution_icon_url . "http://cdn.sstatic.net/superusermeta/img/apple-touch-icon@2.png")
  (site_state . "linked_meta")
  (markdown_extensions . ("Prettify"))
  (related_sites . (((name . "Super User")
		     (site_url . "http://superuser.com")
		     (api_site_parameter . "superuser")
		     (relation . "parent"))
		    ((name . "Chat Stack Exchange")
		     (site_url . "http://chat.stackexchange.com")
		     (relation . "chat"))))
  (styling
   (link_color . "#0077CC")
   (tag_foreground_color . "#000")
   (tag_background_color . "#FFF")))
 ((site_type . "meta_site")
  (name . "Meta Server Fault")
  (logo_url . "http://cdn.sstatic.net/serverfaultmeta/img/logo.png")
  (api_site_parameter . "meta.serverfault")
  (site_url . "http://meta.serverfault.com")
  (audience . "system administrators and IT professionals")
  (icon_url . "http://cdn.sstatic.net/serverfaultmeta/img/apple-touch-icon.png")
  (favicon_url . "http://cdn.sstatic.net/serverfaultmeta/img/favicon.ico")
  (high_resolution_icon_url . "http://cdn.sstatic.net/serverfaultmeta/img/apple-touch-icon@2.png")
  (site_state . "linked_meta")
  (related_sites . (((name . "Server Fault")
		     (site_url . "http://serverfault.com")
		     (api_site_parameter . "serverfault")
		     (relation . "parent"))
		    ((name . "Chat Stack Exchange")
		     (site_url . "http://chat.stackexchange.com")
		     (relation . "chat"))))
  (styling
   (link_color . "#0077CC")
   (tag_foreground_color . "#000")
   (tag_background_color . "#FFF")))
 ((site_type . "main_site")
  (name . "Geographic Information Systems")
  (logo_url . "http://cdn.sstatic.net/gis/img/logo-small.png")
  (api_site_parameter . "gis")
  (site_url . "http://gis.stackexchange.com")
  (audience . "cartographers, geographers and GIS professionals")
  (icon_url . "http://cdn.sstatic.net/gis/img/apple-touch-icon.png")
  (favicon_url . "http://cdn.sstatic.net/gis/img/favicon.ico")
  (twitter_account . "StackGIS")
  (high_resolution_icon_url . "http://cdn.sstatic.net/gis/img/apple-touch-icon@2.png")
  (site_state . "normal")
  (closed_beta_date . 1279756800)
  (open_beta_date . 1280361600)
  (launch_date . 1299456000)
  (markdown_extensions . ("Prettify"))
  (related_sites . (((name . "Geographic Information Systems Meta Stack Exchange")
		     (site_url . "http://meta.gis.stackexchange.com")
		     (api_site_parameter . "meta.gis")
		     (relation . "meta"))
		    ((name . "Chat Stack Exchange")
		     (site_url . "http://chat.stackexchange.com")
		     (relation . "chat"))))
  (styling
   (link_color . "#176F8C")
   (tag_foreground_color . "#696969")
   (tag_background_color . "#f5f5f5")))
 ((site_type . "meta_site")
  (name . "Geographic Information Systems Meta")
  (logo_url . "http://cdn.sstatic.net/gismeta/img/logo-small.png")
  (api_site_parameter . "meta.gis")
  (site_url . "http://meta.gis.stackexchange.com")
  (audience . "cartographers, geographers and GIS professionals")
  (icon_url . "http://cdn.sstatic.net/gismeta/img/apple-touch-icon.png")
  (favicon_url . "http://cdn.sstatic.net/gismeta/img/favicon.ico")
  (high_resolution_icon_url . "http://cdn.sstatic.net/gismeta/img/apple-touch-icon@2.png")
  (site_state . "linked_meta")
  (related_sites . (((name . "Geographic Information Systems Stack Exchange")
		     (site_url . "http://gis.stackexchange.com")
		     (api_site_parameter . "gis")
		     (relation . "parent"))
		    ((name . "Chat Stack Exchange")
		     (site_url . "http://chat.stackexchange.com")
		     (relation . "chat"))))
  (styling
   (link_color . "#3D3D3D")
   (tag_foreground_color . "#666666")
   (tag_background_color . "#FFF")))
 ((site_type . "main_site")
  (name . "TeX - LaTeX")
  (logo_url . "http://cdn.sstatic.net/tex/img/logo.png")
  (api_site_parameter . "tex")
  (site_url . "http://tex.stackexchange.com")
  (audience . "users of TeX, LaTeX, ConTeXt, and related typesetting systems")
  (icon_url . "http://cdn.sstatic.net/tex/img/apple-touch-icon.png")
  (favicon_url . "http://cdn.sstatic.net/tex/img/favicon.ico")
  (twitter_account . "StackTeX")
  (high_resolution_icon_url . "http://cdn.sstatic.net/tex/img/apple-touch-icon@2.png")
  (site_state . "normal")
  (closed_beta_date . 1280102400)
  (open_beta_date . 1280707200)
  (launch_date . 1289433600)
  (markdown_extensions . ("Prettify"))
  (related_sites . (((name . "TeX - LaTeX Meta Stack Exchange")
		     (site_url . "http://meta.tex.stackexchange.com")
		     (api_site_parameter . "meta.tex")
		     (relation . "meta"))
		    ((name . "Chat Stack Exchange")
		     (site_url . "http://chat.stackexchange.com")
		     (relation . "chat"))))
  (styling
   (link_color . "#0077CC")
   (tag_foreground_color . "#444444")
   (tag_background_color . "#FEFEFA")))
 ((site_type . "meta_site")
  (name . "TeX - LaTeX Meta")
  (logo_url . "http://cdn.sstatic.net/texmeta/img/logo.png")
  (api_site_parameter . "meta.tex")
  (site_url . "http://meta.tex.stackexchange.com")
  (audience . "users of TeX, LaTeX, ConTeXt, and related typesetting systems")
  (icon_url . "http://cdn.sstatic.net/texmeta/img/apple-touch-icon.png")
  (favicon_url . "http://cdn.sstatic.net/texmeta/img/favicon.ico")
  (high_resolution_icon_url . "http://cdn.sstatic.net/texmeta/img/apple-touch-icon@2.png")
  (site_state . "linked_meta")
  (related_sites . (((name . "TeX - LaTeX Stack Exchange")
		     (site_url . "http://tex.stackexchange.com")
		     (api_site_parameter . "tex")
		     (relation . "parent"))
		    ((name . "Chat Stack Exchange")
		     (site_url . "http://chat.stackexchange.com")
		     (relation . "chat"))))
  (styling
   (link_color . "#3D3D3D")
   (tag_foreground_color . "#666666")
   (tag_background_color . "#FFF")))
 ((site_type . "main_site")
  (name . "Ask Ubuntu")
  (logo_url . "http://cdn.sstatic.net/askubuntu/img/logo.png")
  (api_site_parameter . "askubuntu")
  (site_url . "http://askubuntu.com")
  (audience . "Ubuntu users and developers")
  (icon_url . "http://cdn.sstatic.net/askubuntu/img/apple-touch-icon.png")
  (favicon_url . "http://cdn.sstatic.net/askubuntu/img/favicon.ico")
  (twitter_account . "AskUbuntu")
  (high_resolution_icon_url . "http://cdn.sstatic.net/askubuntu/img/apple-touch-icon@2.png")
  (site_state . "normal")
  (closed_beta_date . 1280275200)
  (open_beta_date . 1280880000)
  (launch_date . 1286668800)
  (markdown_extensions . ("Prettify"))
  (aliases . ("http://ubuntu.stackexchange.com"))
  (related_sites . (((name . "Ask Ubuntu Meta")
		     (site_url . "http://meta.askubuntu.com")
		     (api_site_parameter . "meta.askubuntu")
		     (relation . "meta"))
		    ((name . "Chat Stack Exchange")
		     (site_url . "http://chat.stackexchange.com")
		     (relation . "chat"))))
  (styling
   (link_color . "#333333")
   (tag_foreground_color . "#5E5E5E")
   (tag_background_color . "#E8E7E5")))
 ((site_type . "meta_site")
  (name . "Ask Ubuntu Meta")
  (logo_url . "http://cdn.sstatic.net/askubuntumeta/img/logo.png")
  (api_site_parameter . "meta.askubuntu")
  (site_url . "http://meta.askubuntu.com")
  (audience . "Ubuntu users and developers")
  (icon_url . "http://cdn.sstatic.net/askubuntumeta/img/apple-touch-icon.png")
  (favicon_url . "http://cdn.sstatic.net/askubuntumeta/img/favicon.ico")
  (high_resolution_icon_url . "http://cdn.sstatic.net/askubuntumeta/img/apple-touch-icon@2.png")
  (site_state . "linked_meta")
  (aliases . ("http://meta.ubuntu.stackexchange.com"))
  (related_sites . (((name . "Ask Ubuntu")
		     (site_url . "http://askubuntu.com")
		     (api_site_parameter . "askubuntu")
		     (relation . "parent"))
		    ((name . "Chat Stack Exchange")
		     (site_url . "http://chat.stackexchange.com")
		     (relation . "chat"))))
  (styling
   (link_color . "#222222")
   (tag_foreground_color . "#5E5E5E")
   (tag_background_color . "#E8E7E5"))))
